name: crosschat
main: com.thomas15v.crossserver.crosschat.BukkitPlugin
version: ${project.version}b-${build.number}
depend: [CrossServer]
command:
  msg:
    alias: [a]
    description: Messages a player
    usage: /<command>
  reply:
   alias: [r]
   description: Replies a player
   usage: /<command>